// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "task_manager/Domain"

	mock "github.com/stretchr/testify/mock"
)

// TaskUsecases is an autogenerated mock type for the TaskUsecases type
type TaskUsecases struct {
	mock.Mock
}

// CreateTask provides a mock function with given fields: ctx, task, userId
func (_m *TaskUsecases) CreateTask(ctx context.Context, task *domain.Task, userId string) error {
	ret := _m.Called(ctx, task, userId)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Task, string) error); ok {
		r0 = rf(ctx, task, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTask provides a mock function with given fields: ctx, taskId
func (_m *TaskUsecases) DeleteTask(ctx context.Context, taskId string) error {
	ret := _m.Called(ctx, taskId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, taskId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllTasks provides a mock function with given fields: ctx, userId
func (_m *TaskUsecases) GetAllTasks(ctx context.Context, userId string) ([]*domain.Task, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTasks")
	}

	var r0 []*domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Task, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.Task); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTaskByID provides a mock function with given fields: ctx, taskId
func (_m *TaskUsecases) GetTaskByID(ctx context.Context, taskId string) (*domain.Task, error) {
	ret := _m.Called(ctx, taskId)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskByID")
	}

	var r0 *domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Task, error)); ok {
		return rf(ctx, taskId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Task); ok {
		r0 = rf(ctx, taskId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, taskId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTask provides a mock function with given fields: ctx, taskId, task
func (_m *TaskUsecases) UpdateTask(ctx context.Context, taskId string, task *domain.Task) (*domain.Task, error) {
	ret := _m.Called(ctx, taskId, task)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 *domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *domain.Task) (*domain.Task, error)); ok {
		return rf(ctx, taskId, task)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *domain.Task) *domain.Task); ok {
		r0 = rf(ctx, taskId, task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *domain.Task) error); ok {
		r1 = rf(ctx, taskId, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTaskUsecases creates a new instance of TaskUsecases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskUsecases(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskUsecases {
	mock := &TaskUsecases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
